In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [42]:
samples = pd.read_csv("sample_list.csv",sep=';') #load sample list
df = pd.DataFrame(samples)
samples_df = df[['Sample', 'Disease']]
samples_df.head()

                Sample  Disease
0  Sample_0001_Non-LCa  Non-LCa
1  Sample_0002_Non-LCa  Non-LCa
2      Sample_0003_LCa      LCa
3  Sample_0004_Non-LCa  Non-LCa
4  Sample_0005_Non-LCa  Non-LCa

In [43]:
mirnas = pd.read_csv("norm_data__non_log.txt",sep='\t') #load miRNAs

In [44]:
mirnas.head()

,Sample_0001_Non-LCa,Sample_0002_Non-LCa,Sample_0003_LCa,Sample_0004_Non-LCa,Sample_0005_Non-LCa,Sample_0006_Non-LCa,Sample_0007_Non-LCa,Sample_0008_Non-LCa,Sample_0009_Non-LCa,Sample_0010_Non-LCa,...,Sample_3037_Non-LCa,Sample_3038_Non-LCa,Sample_3039_Non-LCa,Sample_3040_Non-LCa,Sample_3041_Non-LCa,Sample_3042_Non-LCa,Sample_3043_LCa,Sample_3044_Non-LCa,Sample_3045_Non-LCa,Sample_3046_Non-LCa
feature-0001,8.500863,9.941665,8.468764,8.519110,7.695362,8.511572,9.806796,8.111616,7.452919,7.578256,...,8.393852,9.336868,8.825555,11.023160,7.890167,8.842462,6.860710,7.650270,7.415795,7.797602
feature-0002,8.001125,8.064157,7.945632,7.428407,7.969229,7.596385,7.350761,7.766351,7.596385,7.501078,...,7.974236,7.603061,7.046157,7.239167,7.988912,8.037061,8.251054,7.385154,7.998785,8.003537
feature-0003,28.747845,15.727566,35.426976,13.942995,33.991915,36.450612,7.784135,28.747845,62.300418,16.526670,...,35.426976,43.689084,38.073203,15.543100,34.456610,38.622678,43.689084,59.966780,89.553106,30.980816
feature-0004,9.941665,12.098506,10.311829,14.085761,11.822439,10.815340,23.271599,9.806796,10.024888,10.592802,...,9.100630,12.870063,11.323305,12.442595,12.293139,9.982537,11.171948,9.469426,8.069276,9.842943
feature-0005,7.589673,8.853987,7.648110,8.174631,8.940175,8.519110,9.304344,7.806593,9.084872,9.038317,...,7.589673,8.565147,8.245406,8.203915,7.315470,8.342968,8.871970,7.269378,8.448181,7.764134

In [45]:
mirnas_df=mirnas.T

In [46]:
mirnas_df.head()

,feature-0001,feature-0002,feature-0003,feature-0004,feature-0005,feature-0006,feature-0007,feature-0008,feature-0009,feature-0010,...,feature-1174,feature-1175,feature-1176,feature-1177,feature-1178,feature-1179,feature-1180,feature-1181,feature-1182,feature-1183
Sample_0001_Non-LCa,8.500863,8.001125,28.747845,9.941665,7.589673,8.679772,7.804306,13.542269,7.080440,21.135280,...,7.713066,7.652475,7.600870,9.076837,7.395667,85.931773,303.242753,8.960097,12.928830,8.549728
Sample_0002_Non-LCa,9.941665,8.064157,15.727566,12.098506,8.853987,9.100630,8.214993,13.105117,6.445316,14.939257,...,7.312545,6.763480,7.455388,8.444764,7.232966,73.140879,179.976799,8.814242,19.714151,8.259411
Sample_0003_LCa,8.468764,7.945632,35.426976,10.311829,7.648110,8.761466,7.772970,16.314979,7.489190,27.411820,...,7.750865,7.326394,7.757589,8.493571,9.578714,30.190762,175.608275,8.084079,11.171948,8.751308
Sample_0004_Non-LCa,8.519110,7.428407,13.942995,14.085761,8.174631,8.049387,8.358423,12.596805,7.715340,21.532998,...,8.327567,7.860627,8.256623,9.406866,8.393852,20.942159,269.352082,8.410467,9.382674,8.185181
Sample_0005_Non-LCa,7.695362,7.969229,33.991915,11.822439,8.940175,8.101449,7.306996,9.092907,6.889294,39.199841,...,7.675295,8.303378,7.450536,11.606221,10.392308,18.084913,367.711493,7.670650,11.869036,13.737306

In [55]:
mirnas_df1 = mirnas_df.iloc[:,0:1183]  #selecting column from miRNS

In [48]:
samples_df.head()

                Sample  Disease
0  Sample_0001_Non-LCa  Non-LCa
1  Sample_0002_Non-LCa  Non-LCa
2      Sample_0003_LCa      LCa
3  Sample_0004_Non-LCa  Non-LCa
4  Sample_0005_Non-LCa  Non-LCa

In [56]:
samples_df1 = samples_df.iloc[:,-1] #output column

In [57]:
samples_df1.head()

0    Non-LCa
1    Non-LCa
2        LCa
3    Non-LCa
4    Non-LCa
Name: Disease, dtype: object

In [62]:
#Univariate feature selection
#apply SelectKBest
select_feature = SelectKBest(score_func=chi2, k=30)
fit = select_feature.fit(mirnas_df1,samples_df1)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(mirnas_df1.columns)
#concat two dataframes for better visualization 
Scores = pd.concat([dfcolumns,dfscores],axis=1)
Scores.columns = ['Features','Score']
#print best 30 features with scores
print(Scores.nlargest(30,'Score'))

          Features         Score
861   feature-0862  2.298243e+06
60    feature-0061  2.224120e+06
572   feature-0573  1.708709e+06
855   feature-0856  1.082321e+06
1135  feature-1136  7.871919e+05
461   feature-0462  6.237259e+05
852   feature-0853  5.698531e+05
1072  feature-1073  5.691676e+05
1047  feature-1048  4.934103e+05
532   feature-0533  4.792379e+05
272   feature-0273  4.258282e+05
1157  feature-1158  4.255120e+05
299   feature-0300  3.632446e+05
869   feature-0870  3.625550e+05
1087  feature-1088  3.595284e+05
28    feature-0029  3.129633e+05
432   feature-0433  2.968598e+05
597   feature-0598  2.713446e+05
975   feature-0976  2.709437e+05
696   feature-0697  2.681633e+05
366   feature-0367  2.628777e+05
410   feature-0411  2.616452e+05
811   feature-0812  2.543454e+05
1171  feature-1172  2.513917e+05
47    feature-0048  2.440689e+05
615   feature-0616  2.429623e+05
349   feature-0350  2.322512e+05
509   feature-0510  2.288162e+05
693   feature-0694  2.225215e+05
56    feature-0057  2.046931e+05